name: 🟢 Good First Issue
description: A beginner-friendly task for new contributors
title: "[GOOD FIRST ISSUE] "
labels: ["good first issue", "hacktoberfest"]
body:
  - type: markdown
    attributes:
      value: |
        This is a beginner-friendly issue perfect for first-time contributors!

  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Describe the task clearly and concisely
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: helpful-links
    attributes:
      label: Helpful Resources
      description: Links to documentation, examples, or guides
      placeholder: |
        - [Next.js Documentation](https://nextjs.org/docs)
        - [Tailwind CSS](https://tailwindcss.com/docs)
        - [TypeScript Handbook](https://www.typescriptlang.org/docs/)

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of task is this?
      options:
        - UI/UX Design
        - New Feature
        - Bug Fix
        - Documentation
        - Testing
        - Performance
        - Accessibility
    validations:
      required: true

  - type: textarea
    id: getting-started
    attributes:
      label: Getting Started
      description: How should a new contributor approach this?
      placeholder: Step-by-step guide for getting started with this issue
    validations:
      required: true